//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot assign keys.
        /// </summary>
        internal static string CannotAssignMultipleKeysCaption {
            get {
                return ResourceManager.GetString("CannotAssignMultipleKeysCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot assign multiple keys to one action.
        /// </summary>
        internal static string CannotAssignMultipleKeysText {
            get {
                return ResourceManager.GetString("CannotAssignMultipleKeysText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element not selected.
        /// </summary>
        internal static string ElementNotSelectedText {
            get {
                return ResourceManager.GetString("ElementNotSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element selected.
        /// </summary>
        internal static string ElementSelectedText {
            get {
                return ResourceManager.GetString("ElementSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End game session.
        /// </summary>
        internal static string EndGameSessionCaption {
            get {
                return ResourceManager.GetString("EndGameSessionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to end your current game session? 
        ///Your results will be saved..
        /// </summary>
        internal static string EndGameSessionText {
            get {
                return ResourceManager.GetString("EndGameSessionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EraseCursor {
            get {
                object obj = ResourceManager.GetObject("EraseCursor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Error {
            get {
                object obj = ResourceManager.GetObject("Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string ExitMessageBoxCaption {
            get {
                return ResourceManager.GetString("ExitMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit?.
        /// </summary>
        internal static string ExitMessageBoxText {
            get {
                return ResourceManager.GetString("ExitMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit without saving current map?.
        /// </summary>
        internal static string ExitWithoutSavingCurrentMap {
            get {
                return ResourceManager.GetString("ExitWithoutSavingCurrentMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GoBackArrow {
            get {
                object obj = ResourceManager.GetObject("GoBackArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name.
        /// </summary>
        internal static string ListContainsMapWithSameNameCaption {
            get {
                return ResourceManager.GetString("ListContainsMapWithSameNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map list already contains map with the same name.
        ///Enter a different name..
        /// </summary>
        internal static string ListContainsMapWithSameNameText {
            get {
                return ResourceManager.GetString("ListContainsMapWithSameNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MapBackground {
            get {
                object obj = ResourceManager.GetObject("MapBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum player count exceeded.
        /// </summary>
        internal static string MaxPlayerCountExceededCaption {
            get {
                return ResourceManager.GetString("MaxPlayerCountExceededCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player count can&apos;t exceed .
        /// </summary>
        internal static string MaxPlayerCountExceededText {
            get {
                return ResourceManager.GetString("MaxPlayerCountExceededText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MenuLogo {
            get {
                object obj = ResourceManager.GetObject("MenuLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No player on map.
        /// </summary>
        internal static string NoPlayerPlacedCaption {
            get {
                return ResourceManager.GetString("NoPlayerPlacedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No player is placed on current map.
        /// </summary>
        internal static string NoPlayerPlacedText {
            get {
                return ResourceManager.GetString("NoPlayerPlacedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No prize placed.
        /// </summary>
        internal static string NoPrizePlacedCaption {
            get {
                return ResourceManager.GetString("NoPrizePlacedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No prize is placed on current map.
        /// </summary>
        internal static string NoPrizePlacedText {
            get {
                return ResourceManager.GetString("NoPrizePlacedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string PauseMessageBoxCaption {
            get {
                return ResourceManager.GetString("PauseMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game is paused.
        ///
        ///Press OK to resume..
        /// </summary>
        internal static string PauseMessageBoxText {
            get {
                return ResourceManager.GetString("PauseMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player_Left {
            get {
                object obj = ResourceManager.GetObject("Player_Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player_Right {
            get {
                object obj = ResourceManager.GetObject("Player_Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Prize {
            get {
                object obj = ResourceManager.GetObject("Prize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SelectCursor {
            get {
                object obj = ResourceManager.GetObject("SelectCursor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Trap {
            get {
                object obj = ResourceManager.GetObject("Trap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wall {
            get {
                object obj = ResourceManager.GetObject("Wall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
